# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

vanillaconfig_version =1.2.18+26.3
mod_menu_version = 20.0.0-alpha.1

# Mod Properties
mod_version = 1.4.5+26.3
maven_group = net.treset
archives_base_name = ridehud

# Dependencies
fabric_api_version=0.160.5+26.3
